### ISSUE TITLE
block number is not increasing on testnet

### ISSUE THREAD

**Issue by AaronKutch** [neonevm/proxy-model.py#1001]
I have the files to reproduce this https://github.com/AaronKutch/block_number_bug . Run `bash reprod.sh` (note you can replace `curl_container.dockerfile` with whatever you already have cached that has `curl`) and it will bring up a solana-neon localnet with a container `curl_container` that you can get a shell for and query the proxy with. The `eth_calls.sh` has lines you can paste in order:
- request funds for the 0xBf... account
- look at the balances of the accounts
- make a raw transaction to the 0xb3... account
- check the balances again to see that they have changed
- get the transaction by hash
- check the block numbers

The problem is that a raw transaction is seemingly registered (the target address has its "latest" balance increased without being included in a block which is usually impossible on other chains), but a new block is never minted to include it, the block statistics are all either "null" or 0. This breaks our integration tests that expect block numbers to increase (preferably instantly, or there needs to be a way to configure quick block production) and include transactions made.

**Comment by afalaleev** [comment]
You have removed the indexer container from the docker-compose.
https://github.com/neonlabsorg/proxy-model.py/blob/018c41ff6542f79c9078c4260ad10ce373a57b7c/proxy/docker-compose-test.yml#L198-L221

It is its task to index blocks and transactions from Solana blocks in the Ethereum format.

**Comment by AaronKutch** [comment]
Thanks, I thought it was optional
