### ISSUE TITLE
Self-contained networks cannot be made

### ISSUE THREAD

**Issue by AaronKutch** [neonevm/proxy-model.py#1002]
https://github.com/AaronKutch/block_number_bug has reproducible scripts for a local net that isn't entirely local yet. On the line `docker network create net` if you add `--internal` the solana container will end up exiting with
```
Error: RPC request error: cluster version query failed: error sending request for url (https://api.mainnet-beta.solana.com/): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
```
For various reasons we do not want our integration tests making remote queries. If this is expected behavior with the docker-compose.yml file, can there be a flag or something to turn off remote queries?

**Comment by afalaleev** [comment]
@AaronKutch  
This problem was resolved in the neon-evm.
You should upgrade your version of neon-evm to the v0.13.0 (or latest).

**Comment by AaronKutch** [comment]
thanks
