### ISSUE TITLE
OpenZeppelin unit test fails. Uncaught Error: The send transactions "from" field must be defined!

### ISSUE THREAD

**Issue by s-medvedev** [neonevm/proxy-model.py#278]
@mich-master commented on [Thu Sep 16 2021](https://github.com/neonlabsorg/neon-evm/issues/246)

**Impact:**
_Proxy + Neon EVM <-> OpenZeppelin library compatibility_

**STR:**

1. Set up Truffle environment for the OpenZeppelin library as described
#219
2. Run the unit test for "AccessControl" contract
`truffle --network solana test ./test/access/AccessControl.test.js`
 

**Actual result:**
Failure message:
Contract: AccessControl
     "after each" hook: after test for "non-admin cannot grant role to other accounts":
     Uncaught Error: The send transactions "from" field must be defined!

**Expected result:**
Test passed successfully.

---

@rozhkovdmitrii commented on [Tue Oct 12 2021](https://github.com/neonlabsorg/neon-evm/issues/246#issuecomment-941048635)

![image](https://user-images.githubusercontent.com/801971/136971766-a3fc315e-3407-466c-a6e7-da4956a845b6.png)

Let it be here )

**Comment by ivandzen** [comment]
Was unable to reproduce nether with neon-compatibility (hardhat) nor with truffle. Bug not confirmed with newer version of proxy

**Comment by ivandzen** [comment]
Was unable to reproduce nether with neon-compatibility (hardhat) nor with truffle. Bug not confirmed with newer version of proxy
