### ISSUE TITLE
Process `UpdateValidsTable` instruction in indexer

### ISSUE THREAD

**Issue by s-medvedev** [neonevm/proxy-model.py#301]
@s-medvedev commented on [Thu Nov 18 2021](https://github.com/neonlabsorg/neon-evm/issues/380)

Does the indexer know about the new instruction?

_Originally posted by @vasiliy-zaznobin in https://github.com/neonlabsorg/neon-evm/pull/379#discussion_r751967469_

**Comment by afalaleev** [comment]
Implementing update-valids indexing is very costly, but doesn't give us any useful information.
Simpler to get full list of accounts and run update-valids for every found account.
