### ISSUE TITLE
Implement performance metrics for airdropper

### ISSUE THREAD

**Issue by ivandzen** [neonevm/proxy-model.py#392]
It is required to collect performance metrics for airdropper:

* Trigger transaction rate - how many trigger transactions (generated by NeonPass) was produced during some period
* How many airdrops performed during some period
* How many error and for what reason occured during some period

To satisfy this requirement it is suggested to collect events into DB tables:

* **airdrop_ready** with columns: 
            eth_address     - target address of input liquidity transaction
            scheduled_ts   - timestamp when trigger transaction found
            finished_ts       - timestamp when airdrop finished
            duration           = finished_ts - scheduled_ts
            amount_galans  - amount of galans airdropped
* **failed_airdrop_attempts** with columns:
            attempt_time    - timestamp when airdrop attempt failed
            eth_address     - target address of input liquidity transaction
            reason              - reason of failure

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-215) by [Unito](https://www.unito.io)

**Comment by vasiliy-zaznobin** [comment]
@ivandzen  Please describe what should be implemented and who and how can use it.
