### ISSUE TITLE
the insertion into OPERATOR_COST table causes an error "Connection timeout" from client side

### ISSUE THREAD

**Issue by sinev-valentine** [neonevm/proxy-model.py#393]
It is necessary to investigate the problem connected with the "insert" operator, table fields types, etc

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-216) by [Unito](https://www.unito.io)

**Comment by s-medvedev** [comment]
@vodolaz We need to enable `WRITE_TRANSACTION_COST_IN_DB` on our nightstand and run the openzeppelin tests.

**Comment by vodolaz** [comment]
@s-medvedev job with tests in the queue
