### ISSUE TITLE
Last run on night-stand shows a lot of errors: 'Failed to read account permissions. Try to repeat later'

### ISSUE THREAD

**Issue by afalaleev** [neonevm/proxy-model.py#527]
This is a root cause of down of night-stand results.
https://docs.neon-labs.org/neon-compatibility/587/#suites/5fa4cabce0b03a0b3ff99d0a44d2aeb4/f57d36aa9070d200/

```
Returned error: Failed to read account permissions. Try to repeat later
Error: Returned error: Failed to read account permissions. Try to repeat later
    at Context.<anonymous> (test/governance/Governor.test.js:35:22)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-245) by [Unito](https://www.unito.io)

**Comment by vasiliy-zaznobin** [comment]
@gigimon it is required to check whether this error appears on the night stand

**Comment by gigimon** [comment]
@vasiliy-zaznobin i checked last two night runs and this error didn't reproduce. I think we can close this ticket
