### ISSUE TITLE
Interface to get statistics for operators

### ISSUE THREAD

**Issue by otselnik** [neonevm/proxy-model.py#575]
* [x] How many SOLs are they spend in Neon transaction (per iteration and accumulated)
* [x] How many NEONs are they received.
* [x] How many BPF cycles was used in each iteration (proxy-model-py#447)
* [x] How many Neon transactions were completed (independ on status)
* [x] How many Neon transactions were canceled
* [x] Return postgres availability 
* [x] Return Solana node status
* [x] Operator balance
* [x] Minimal gas price environment value

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-256) by [Unito](https://www.unito.io)

**Comment by rozhkovdmitrii** [comment]
Had been gotten by @vodolaz and solved with prometheteus
