### ISSUE TITLE
Transaction execution fails with the minimum allowable price

### ISSUE THREAD

**Issue by afalaleev** [neonevm/proxy-model.py#599]
Error: Returned error: The transaction gasPrice is less than the minimum allowable value(364111000000<364122000000.0000000)

Error: Returned error: The transaction gasPrice is less than the minimum allowable value(363242000000<363682000000.0000000)

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-264) by [Unito](https://www.unito.io)

**Comment by gigimon** [comment]
Moreover this error exist in proxy log with traceback on devnet
req_id: 691ee6d

```
Exception on process request. Type(err): , Error: The transaction gasPrice is less than the minimum allowable value(400000000000<437870246000), Traceback:   File "/opt/proxy/plugin/solana_rest_api.py", line 445, in process_request
```
