### ISSUE TITLE
Proxy doesn't create new attempt if get "Error: ComputationalBudgetExceeded"

### ISSUE THREAD

**Issue by gigimon** [neonevm/proxy-model.py#637]
I have found a problem when test MoraSwap staking. Our proxy receive "Error: ComputationalBudgetExceeded" and stop new attempts to operate with this.

Steps to reproduce:
1. Go to moraswap.com -> Stake
2. Enter amount
3. Click "Approve"
4. Approve transaction in metamask and wait Failed state

[Elasticsearch link](https://es.neonlabs.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-15T09:15:47.000Z',to:'2022-03-15T09:15:48.000Z'))&_a=(columns:!(),filters:!(),index:e4a7a690-a3a0-11ec-b896-63650381ee07,interval:auto,query:(language:kuery,query:'req_id%20:%2073aed5b'),sort:!(!(timestamp,desc))))

**Comment by afalaleev** [comment]
The problem was in resize contract storage.
