### ISSUE TITLE
Buildkite pipeline is failed after a merge

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/proxy-model.py#672]
# Impact

Buildkite fetches wrong revision on preparing working directory step. Relates to both: proxy-model.py and evm-loader repositories.

# Samples

You can look at broken pipelines by the following links:

[neon-proxy](https://buildkite.com/cyberway/neon-proxy/builds/5199)
[neon-evm](https://buildkite.com/cyberway/evm-loader/builds/3478#cc67016a-a441-4f66-b4c7-67db83b96fcf)

# Description

The `git fetch` command relates to the wrong and the same pull request every time the build is failed.

## Wrong environment:

![image.png](https://images.zenhubusercontent.com/61486e106770da2887220c4a/58d2f272-8ca7-44df-a641-db6d50be01f6)

## Wrong fetch

![image.png](https://images.zenhubusercontent.com/61486e106770da2887220c4a/5441e2fe-f4ef-4326-8aea-ffd18b19838f)

# Participants

@s-medvedev @rozhkovdmitrii @vodolaz are aware of the problem

**Comment by inkognitotester** [comment]
Not reproducible
