### ISSUE TITLE
Emulator Error message: AccountUnitialized while Moraswap creating liquidity pool

### ISSUE THREAD

**Issue by mich-master** [neonevm/proxy-model.py#684]
Creating liquidity pair NEON <-> SUSHI in Moraswap dApp
https://dev.moraswap.com/exchange/pool
finishes with error

> `Error message: AccountUnitialized`

STR:
Open "Liquidity" page in Moraswap
https://dev.moraswap.com/exchange/pool
try to add liquidity pool for the pair NEON <-> SUSHI

Actual result:
Liquidity pool doesn't create with RPC error message. Error message: AccountUnitialized

Expected result:
Liquidity pool created.

**Comment by afalaleev** [comment]
The error message is another: ```Emulator error: AccountUnitialized```
