### ISSUE TITLE
eth_getBlockByNumber and eth_getBlockByHash provides different info

### ISSUE THREAD

**Issue by ivandzen** [neonevm/proxy-model.py#775]
eth_getBlockByHash return Null when being called first time for given block. Result eth_getBlockByHash bacomes correct after calling eth_getBlockByNumber once for this block.

1. FIRST CALL eth_getBlockByHash
![](https://user-images.githubusercontent.com/6882119/169056386-e65f743d-e841-49c6-bfbf-94fe7ac1c9b7.png)
1. FIRST CALL eth_getBlockByNumber
![](https://user-images.githubusercontent.com/6882119/169056677-32003d2b-3d39-495c-9667-961ce654de39.png)
1. SECOND CALL eth_getBlockByHash
![](https://user-images.githubusercontent.com/6882119/169056838-016af4f6-0d7d-4f49-a851-9ae4d6b1990d.png)

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-99) by [Unito](https://www.unito.io)

**Comment by afalaleev** [comment]
Moved to Jira
