### ISSUE TITLE
Moraswap transaction size more than 1232

### ISSUE THREAD

**Issue by gigimon** [neonevm/proxy-model.py#797]
When we create a new liquidity pair we get error about transaction size.

```
'{"value":{"code":-32603,"data":{"code":-32000,"message":"transaction too large: 1234 > 1232"}}}
```

Issue in support https://github.com/neonlabsorg/neon-support/issues/35

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-87) by [Unito](https://www.unito.io)

**Comment by afalaleev** [comment]
Moved to Jira
