### ISSUE TITLE
Save and get confirmed state in indexer

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/proxy-model.py#810]
# Impact

A significant part of DAPs use different Neon proxy instances to make transactions and to check the status. It means the global one to send raw transactions and the local one to get receipt, logs and the like. In this case there is no possibility to trace confirmed but not finalized state from different Neon Proxy instances but it should be to make able the DAPs provide their own the logic.

That's why the indexer should provide the both confirmed and finalized states to proxy instances.

**Comment by afalaleev** [comment]
Moved to Jira
