### ISSUE TITLE
There are no artifacts if step is finished by timeout

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/proxy-model.py#816]
# Impact

In some cases a CI step can take to much time. In this case there are no any artifacts to analyse on the `Artifacts` page

# TODO

If it's possible, catch please timeout event and manage with uploading the artifacts

# Buildkite CI build

https://buildkite.com/cyberway/neon-proxy/builds/6568#01819bc4-9da3-4d04-a1b5-6ed4cf31c6f6

**Comment by afalaleev** [comment]
Moved to Jira
