### ISSUE TITLE
Simplify using of proxy Docker-image

### ISSUE THREAD

**Issue by s-medvedev** [neonevm/proxy-model.py#87]
1. Run proxy with evm_loader in the Solana testnet - the most important option for users who will try to work with their proxy. This default behaviour when container run without arguments. In this case:
  - proxy uses SOLANA_URL pointed to Solana testnet
  - proxy communicate with known evm_loader (address will be set in future, when we deploy evm_loader to testnet)
2. Run proxy with local Solana cluster (evm_loader didn't deploy yet). In this case we need to get worked configuration (proxy and evm_loader should work correctly). So proxy should use evm_loader, which located in the Docker-image and deploy it before start.
  - simplify startup with docker-compose.yml (Solana and proxy started in one network)
  - proxy uses SOLANA_URL to connect to the Solana cluster
  - proxy deploy evm_loader and connect to it
3. Run proxy with local Solana cluster and use specified evm_loader. This case can be used by developers.
  - simplify startup with docker-compose.yml (Solana and proxy started in one network)
  - after startup Solana cluster, a developer can deploy evm_loader and specify its address in the EVM_LOADER environment variable
  - proxy uses SOLANA_URL and EVM_LOADER to connect to the Solana cluster and evm_loader

No matter which option is used:
  - Solana account to the proxy can be created at the startup or specified through identity.json.

**Comment by vasiliy-zaznobin** [comment]
Change this ID to define neon-evm address in testnet
https://github.com/neonlabsorg/proxy-model.py/pull/114/files#diff-694ffabc7d01fd7dde3ed7f671ec5733027bb06be51d13412eeeed3a1b4a6937R18
