### ISSUE TITLE
Malformed HTTP response header

### ISSUE THREAD

**Issue by ivandzen** [neonevm/proxy-model.py#987]
Proxy respond with "200\r\n" in the ending but HTTP 1.1 specification declares the right sequence to be "200 OK\r\n"
HTTP 1.1 specification declares Status-Line like this
`Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF`
Reason-Phrase is
`Reason-Phrase  = *<TEXT, excluding CR, LF>`
which means it CAN be empty. BUT spacebar is included in Status-Line which means it still must present before CRLF. Covalent implementation is dependent on this standard.
right response should be `200 \r\n` (with preceeding space) or `200 OK\r\n` according to specification
Refer to [https://www.ietf.org/rfc/rfc2616.txt](https://www.ietf.org/rfc/rfc2616.txt) for details (section **6.1 Status-Line**)

**Comment by afalaleev** [comment]
Moved to Jira
